environment:
  matrix:
  - nodejs_version: "6"
    platform: x64
  - nodejs_version: "6"
    platform: x86
  - nodejs_version: "7"
    platform: x64
  - nodejs_version: "7"
    platform: x86
  - nodejs_version: "8"
    platform: x64
  - nodejs_version: "8"
    platform: x86
  - nodejs_version: "9"
    platform: x64
  - nodejs_version: "9"
    platform: x86
  - nodejs_version: "10"
    platform: x64
  - nodejs_version: "10"
    platform: x86

install:
  - where npm
  - where node
  - ps: Install-Product node $env:nodejs_version $env:platform
  - 'if "%nodejs_version%" LEQ 5 (npm install -g npm@5) else (npm install -g npm@latest)'
  - 'if "%nodejs_version%_%platform%" == "4_x86" (npm config set -g cafile=package.json && npm config set -g strict-ssl=false)'

build: off

artifacts:
  - path: 'build/stage/**/bcrypt*.tar.gz'

test_script:
  - node --version
  - npm --version
  - npm test

on_success:
  - .\node_modules\.bin\node-pre-gyp package
  - ps: if $APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED -like '*publish binary*' { echo "Publishing"; npm install node-pre-gyp-github@1.3.1; ./node_modules/.bin/node-pre-gyp configure; ./node_modules/.bin/node-pre-gyp build; ./node_modules/.bin/node-pre-gyp package; ./node_modules/.bin/node-pre-gyp-github publish --release }
 