name: Build/Deploy on Push

on:
  push:
    branches:
      - master

jobs:
  run:
    name: Build/Deploy on Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      
      - run: npm run copy-types
      
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}